=== mdavid/DDay-iCal-svn/DDay.iCal.Validator/iCalValid/icalvalidSchema/schema.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://icalvalid.wikidot.com/validation"
    xmlns="http://icalvalid.wikidot.com/validation"
    elementFormDefault="qualified">

    <xs:simpleType
        name="datetimeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(-)?[0-9]{4}-?[0-9]{2}-?[0-9]{2}T[0-9]{2}:?[0-9]{2}:?[0-9]{1,2}(\.[0-9]+)?(Z|((\+|-)[0-9]{2}(:?[0-9]{2})?))?" />
        </xs:restriction>        
    </xs:simpleType>

    <xs:simpleType
        name="langIDType">
        <xs:restriction base="xs:token">
            <xs:minLength value="2"/>
            <xs:maxLength value="7"/>
            <xs:pattern value="[a-zA-Z0-9]{2,3}(-[a-zA-Z0-9]{2,3})?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType
        name="nameIDType">
        <xs:restriction base="xs:token">
            <xs:minLength value="2"/>
            <xs:pattern value="[a-zA-Z0-9_]{2,}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType
        name="rulesetRuleType">
        <xs:attribute
            name="name"
            type="nameIDType"
            use="required" />
        <xs:attribute
            name="file"
            type="xs:string"
            use="required" />
    </xs:complexType>

    <xs:complexType
        name="rulesetType">
        <xs:sequence>
            <xs:element
                name="rule"
                type="rulesetRuleType"
                minOccurs="0"
                maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute
            name="name"
            type="nameIDType"
            use="required" />
        <xs:attribute
            name="basedOn"
            type="nameIDType"
            use="optional" />
        <xs:attribute
            name="nameString"
            type="nameIDType"
            use="optional" />
        <xs:attribute
            name="descriptionString"
            type="nameIDType"
            use="optional" />
    </xs:complexType>

    <xs:complexType
        name="rulesetsType">
        <xs:sequence>
            <xs:element
                name="ruleset"
                type="rulesetType"
                minOccurs="1"
                maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType
        name="stringType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name"
                              type="nameIDType"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType
        name="errorType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute
                    name="name"
                    type="nameIDType"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType
        name="resolutionType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute
                    name="error"
                    type="nameIDType"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType
        name="languageType">
        <xs:sequence>
            <xs:element
                name="string"
                type="stringType"
                minOccurs="0"
                maxOccurs="unbounded" />

            <xs:element
                name="errors"
                minOccurs="1"
                maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element
                            name="error"
                            type="errorType"
                            minOccurs="0"
                            maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element
                name="resolutions"
                minOccurs="1"
                maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element
                            name="resolution"
                            type="resolutionType"
                            minOccurs="0"
                            maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute
            name="name"
            type="langIDType"
            use="required" />
        <xs:attribute
            name="description"
            type="xs:string"
            use="optional" />
    </xs:complexType>

    <xs:complexType
        name="failType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="error"
                              type="nameIDType"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType 
        name="passFailStringType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="pass"/>
            <xs:enumeration value="fail"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType
        name="warningErrorStringType">
        <xs:restriction base="xs:string">            
            <xs:enumeration value="warning"/>
            <xs:enumeration value="error"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType
        name="ruleType">
        <xs:choice
            minOccurs="0"
            maxOccurs="unbounded">
            <xs:element
                name="pass"
                type="xs:string" />
            <xs:element
                name="fail"
                type="failType" />
        </xs:choice>
        <xs:attribute
            name="name"
            type="nameIDType"
            use="required" />
    </xs:complexType>

    <xs:complexType
        name="testResultType">        
        <xs:attribute
            name="rule"
            type="nameIDType"
            use="optional" />
        <xs:attribute
            name="expected"
            type="passFailStringType"
            use="optional">            
        </xs:attribute>
        <xs:attribute 
            name="actual"
            type="passFailStringType"
            use="optional">            
        </xs:attribute>
        <xs:attribute
            name="error"
            type="xs:string"
            use="optional" />
        <xs:attribute
            name="errorName"
            type="nameIDType"
            use="optional" />
    </xs:complexType>

    <xs:complexType
        name="validationErrorType">
        <xs:attribute
            name="name"
            type="nameIDType"
            use="required" />
        <xs:attribute
            name="type"
            type="warningErrorStringType"
            use="required" />
        <xs:attribute
            name="message"
            type="xs:string"
            use="optional" />
        <xs:attribute
            name="isFatal"
            type="xs:boolean"
            use="optional" />
        <xs:attribute
            name="line"
            type="xs:integer"
            use="optional" />
        <xs:attribute
            name="col"
            type="xs:integer"
            use="optional" />
    </xs:complexType>

    <xs:complexType
        name="validationResultType">
        <xs:sequence>
            <xs:element
                name="errors"
                minOccurs="0"
                maxOccurs="1">
                <xs:complexType>
                    <xs:sequence
                        minOccurs="0"
                        maxOccurs="unbounded">
                        <xs:element name="error" type="validationErrorType" />                        
                    </xs:sequence>
                </xs:complexType>
            </xs:element>                
        </xs:sequence>
        <xs:attribute
            name="rule"
            type="nameIDType"
            use="required" />
        <xs:attribute
            name="result"
            type="passFailStringType"
            use="required" />
    </xs:complexType>

    <xs:complexType
        name="resultsType">
        <xs:sequence>
            <xs:element
                name="testResults"
                minOccurs="0"
                maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element
                            name="testResult"
                            type="testResultType"
                            minOccurs="0"
                            maxOccurs="unbounded" />
                    </xs:sequence>
                    <xs:attribute
                        name="ruleset"
                        type="nameIDType" />
                </xs:complexType>
            </xs:element>
            <xs:element
                name="validationResults"
                minOccurs="0"
                maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element
                            name="validationResult"
                            type="validationResultType"
                            minOccurs="0"
                            maxOccurs="unbounded" />
                    </xs:sequence>
                    <xs:attribute
                        name="ruleset"
                        type="nameIDType" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute
            name="datetime"
            type="datetimeType" 
            use="optional"/>
        <xs:attribute
            name="language"
            type="langIDType"
            use="optional" />
    </xs:complexType>

    <xs:element
        name="rulesets"
        type="rulesetsType" />
    <xs:element
        name="language"
        type="languageType" />
    <xs:element
        name="rule"
        type="ruleType" />
    <xs:element
        name="results"
        type="resultsType" />
</xs:schema>

=== mdavid/DDay-iCal-svn/DDay.iCal.Validator/iCalValid/icalvalidSchema/languages/gibberish.xml
<?xml version="1.0" encoding="utf-8"?>
<language
    xmlns="http://icalvalid.wikidot.com/validation"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://icalvalid.wikidot.com/validation ../schema.xsd"
    name="en"
    description="English">
    <string name="error">hljkawer</string>
    <string name="warning">xvclkaj</string>
    <string name="line">qwe</string>
    <string name="column">asd</string>
    <string name="pass">ALSD*</string>
    <string name="fail">ZXCV$</string>
    <string name="didNotRun">Alkdi##</string>
    <string name="done">bvaw</string>
    <string name="validatingCalendar">oilk oijll oijlkjalj...</string>
    <string name="loadingCalendar">sdfalkjwe aoijsdf...</string>
    <string name="calendarNotFound">asdflk awljk asdf zxcklvjawer!</string>
    <string name="calendarValid">qwerlkasjd lakjswer laskdfj!</string>
    <string name="noTestsPerformed">v alksdfj zlxckjas oriad.</string>
    <string name="noValidationRuleset">awelk dlkas doja sldkoiawej asdlf; pwyio lkdfja lkaw padoj.</string>
    <string name="performingSelfTest">asd faw;lelrkjas alskdj %1 asdflkjawlek...</string>
    <string name="notAllTestsPerformed">awer asdoija weoapsd asp %1 awerlk ajs, awe asd %2 asdflkja; %3 awsdj asldkfj aasdf.</string>
    <string name="passVsFail">%1 qwer %2 zxcv lkjsdf (%3%)</string>

    <string name="ruleset_Strict_2_0">RU AJL STRICT 2.0</string>
    <string name="ruleset_Strict_2_0_Description">asdlfjaw elkjas dflkajwe rlkasdjf oaiwer</string>
    <string name="ruleset_Compatibility_2_0">RU AJL COMPATIBILITY 2.0</string>
    <string name="ruleset_Compatibility_2_0_Description">a laskj laks poaiwjdlfkj apweiohj sk</string>    

    <errors>
        <error name="passExpectedError">asd fkal aspdoi xcsdf zxlkcvhpa</error>
        <error name="failExpectedError">qw slkdfjp asdjkfp aowrepoishf zx asdfpojaw</error>
        <error name="failWithIncorrectError">a erjasdf oiawjer laksdjf poaiwejr</error>
        <error name="failWithMoreThanOneError">qweirpojias glaweroi asdofhnjapowierh</error>
        <error name="calendarNotLoadedError">qwerasd asdfasdawer asdfawer</error>
        <error name="calendarParseError">qwer aweoriuja sddf aopweirhpoasihf aawersd</error>
        <error name="emptyLineError">qwerasd fjlkajweproiasdj fl;akjwer asdfase</error>
        <error name="crlfPairError">sdfljkcb vn;sn ;lkspoiasdj fpoawie zxckf.</error>
        <error name="versionRequiredError">qwerak sdlk;fj zpoxcbija we;lkaj sdfpoaiwejr l;askdjf paowiejrasdf</error>
        <error name="versionOnlyOnceError">qwerasd sfxcvlk ajsd;flk ajs;krapsdoijzx;lkd jpoaiwe jral;dkfj</error>
        <error name="versionNumberError">asdfaw ejkrapsifj a;lwjkr aspdoi ajwlrkjasdf</error>
        <error name="versionGE2_0Error">asdf awje;lka sdpoiaw erpoiajsd flkajwera</error>
        <error name="prodIDRequiredError">a weproia jsd;lkajw epoaisjd fl;akjwerpoaisd f</error>
        <error name="prodIDOnlyOnceError">asdfalwje rpaoisdjf ;lakje rpaifjawerasdf</error>
    </errors>
    <resolutions>
        <resolution error="emptyLineError">qwerasdawerasdf asdfawerasdf</resolution>
        <resolution error="crlfPairError">asdf jawep;oriajs df;lkajw epoiasdfj pao;wjerasdf</resolution>
        <resolution error="versionRequiredError">sdflk jawepoiasj df;lkajwe rpoaisjd f;lakjerasdf</resolution>
        <resolution error="versionOnlyOnceError">asl kdfjawpeoija s;dflkaj weproiajsd f;lkajwerpoiasdf </resolution>
        <resolution error="prodIDRequiredError">apiowej ra;lskdjf aiowejr a;sldkfj aiowerjasdf</resolution>
        <resolution error="prodIDOnlyOnceError">qwpoeir ajs;ldkf japwoeirj asdl;fkj awpoeriajsdf</resolution>
    </resolutions>    
</language>

=== mdavid/DDay-iCal-svn/DDay.iCal.Validator/iCalValid/icalvalidSchema/rulesets.xml
<?xml version="1.0" encoding="utf-8"?>
<rulesets
    xmlns="http://icalvalid.wikidot.com/validation"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://icalvalid.wikidot.com/validation schema.xsd">
    <!-- 
        Defines the available rulesets for iCalendar validation.        
    -->
    <ruleset
        name="Strict_2_0"
        nameString="ruleset_Strict_2_0"
        descriptionString="ruleset_Strict_2_0_Description">
        
        <!-- General Rules -->
        <rule name="emptyLine" file="rules/RFC2445/emptyLine.xml" />
        <rule name="crlfPairs" file="rules/RFC2445/4.1/crlfPairs.xml" />
        <rule name="lineFolding" file="rules/RFC2445/4.1/lineFolding.xml" />
        <rule name="lineFieldSeparators" file="rules/RFC2445/4.1.1/lineFieldSeparators.xml" />
        <rule name="multipleValues" file="rules/RFC2445/4.1.2/multipleValues.xml" />

        <!-- Calendar Properties -->
        <rule name="version" file="rules/RFC2445/4.6/version.xml" />
        <rule name="prodID" file="rules/RFC2445/4.6/prodID.xml" />
        <rule name="calScale" file="rules/RFC2445/4.6/calScale.xml" />
        <rule name="method" file="rules/RFC2445/4.6/method.xml" />
        
        <!-- Events -->
        <rule name="eventClassProperty" file="rules/RFC2445/4.6.1/eventClassProperty.xml" />
        <rule name="eventCreatedProperty" file="rules/RFC2445/4.6.1/eventCreatedProperty.xml" />
        <rule name="eventEndDurationConflict" file="rules/RFC2445/4.6.1/eventEndDurationConflict.xml" />
    </ruleset>

    <ruleset
        name="Compatibility_2_0"
        nameString="ruleset_Compatibility_2_0"
        descriptionString="ruleset_Compatibility_2_0_Description">
        
        <!-- General Rules -->        
        <rule name="emptyLine" file="rules/RFC2445/emptyLine.xml" />
        <rule name="crlfPairs" file="rules/RFC2445/4.1/crlfPairs.xml" />
        <rule name="lineFolding" file="rules/RFC2445/4.1/lineFolding.xml" />
        <rule name="lineFieldSeparators" file="rules/RFC2445/4.1.1/lineFieldSeparators.xml" />
        <rule name="multipleValues" file="rules/RFC2445/4.1.2/multipleValues.xml" />
        <rule name="inlineBinaryContent" file="rules/RFC2445/4.1.3/inlineBinaryContent.xml" />
        
        <!-- Calendar Properties -->
        <rule name="version" file="rules/RFC2445/4.6/version.xml" />
        <rule name="prodID" file="rules/RFC2445/4.6/prodID.xml" />
        <rule name="calScale" file="rules/RFC2445/4.6/calScale.xml" />
        <rule name="method" file="rules/RFC2445/4.6/method.xml" />

        <!-- Events -->
        <rule name="eventClassProperty" file="rules/RFC2445/4.6.1/eventClassProperty.xml" />
        <rule name="eventCreatedProperty" file="rules/RFC2445/4.6.1/eventCreatedProperty.xml" />
        <rule name="eventEndDurationConflict" file="rules/RFC2445/4.6.1/eventEndDurationConflict.xml" />
    </ruleset>    
</rulesets>

=== mdavid/DDay-iCal-svn/DDay.iCal.Validator/iCalValid/icalvalidSchema/languages/en.xml
<?xml version="1.0" encoding="utf-8"?>
<language
    xmlns="http://icalvalid.wikidot.com/validation"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://icalvalid.wikidot.com/validation ../schema.xsd"
    name="en"
    description="English">
    <string name="error">Error</string>
    <string name="warning">Warning</string>
    <string name="line">Line</string>
    <string name="column">Column</string>
    <string name="pass">Pass</string>
    <string name="fail">Fail</string>
    <string name="didNotRun">Did Not Run</string>   
    <string name="done">Done</string>
    <string name="loadingCalendar">Loading calendar...</string>
    <string name="calendarNotFound">The calendar could not be found!</string>
    <string name="noTestsPerformed">No tests were performed.</string>
    <string name="noValidationRuleset">A validation ruleset could not be determined; Please check the validator name.</string>
    <string name="performingSelfTest">Performing self test using '%1' ruleset...</string>
    <string name="notAllTestsPerformed">There were %1 tests, and only %2 were run; %3 tests did not run.</string>
    <string name="passVsFail">%1 of %2 tests passed (%3%)</string>
    <string name="validatingCalendar">Validating calendar using '%1' ruleset...</string>
    <string name="calendarValid">The calendar is valid!</string>

    <string name="ruleset_Strict_2_0">iCalendar 2.0 Strict</string>
    <string name="ruleset_Strict_2_0_Description">
        Validates iCalendars against the IETF standards in a strict fashion.  Any variations from the standard
        will be reported.
    </string>
    <string name="ruleset_Compatibility_2_0">iCalendar 2.0 Compatibility Mode</string>    
    <string name="ruleset_Compatibility_2_0_Description">
        Validates iCalendars against the IETF standards, ensuring compatibility between known calendaring
        applications whenever possible.  Any practices that are known to break certain calendaring applications
        will be reported.
    </string>

    <errors>
        <error name="passExpectedError">The calendar test expected no errors, but one or more errors occurred:</error>
        <error name="failExpectedError">The calendar test expected exactly one error, but none occurred.</error>
        <error name="failWithIncorrectError">The calendar test expected an error, but failed with a different error than was expected.</error>
        <error name="failWithMoreThanOneError">The calendar test expected exactly one error, but received more than one.</error>
        <error name="calendarNotLoadedError">The calendar could not be loaded.</error>
        <error name="calendarParseError">The calendar could not be parsed due to a serious error in the structure of the calendar.</error>
        <error name="emptyLineError">Empty lines are not allowed, and may not be accepted by all applications.</error>
        <error name="crlfPairError">Line endings must be a Carriage Return/Line Feed (CRLF) pair.</error>
        <error name="propertyRequiredError">The %1 property is required on all %2 components.</error>
        <error name="propertyOnlyOnceError">The %1 property may only be defined once on a %2 component.</error>
        <error name="propertyCountRangeError">The %1 property may only be defined between %3 and %4 times on a %2 component.</error>
        <error name="propertyInvalidValueWarning">The %1 property on %2 components does not officially support the value %3.  The following are defined values: %4.</error>
        <error name="versionRequiredError">The VERSION property is required on all VCALENDAR components.</error>
        <error name="versionOnlyOnceError">The VERSION property may only be defined once on a VCALENDAR component.</error>
        <error name="versionNumberError">The VERSION property is invalid; it must be a version number (i.e. "2.0").</error>
        <error name="versionFirstError">The VERSION property should be the first property on the calendar. Some calendar clients cannot properly parse the calendar otherwise.</error>
        <error name="versionGE2_0Error">Only calendars version 2.0 or higher are allowed.</error>        
        <error name="inlineBinaryContentError">Inline binary content should only be used in special circumstances that demand the iCalendar be expressed as a single object.  See RFC 2445 Section 4.1.3 for details.</error>
        <error name="eventDTEndDurationConflictError">Events MUST only have a DTEND or DURATION, they cannot have both.</error>
    </errors>
    <resolutions>
        <resolution error="emptyLineError">Remove empty lines from the iCalendar.</resolution>        
        <resolution error="crlfPairError">Ensure all line endings are CRLF pairs (US-ASCII decimal 13, followed by US-ASCII decimal 10).</resolution>
        <resolution error="versionRequiredError">Add a VERSION property to the VCALENDAR.  See RFC 2445 section 4.7.4 for details.</resolution>
        <resolution error="versionOnlyOnceError">Remove the second VERSION property from the VCALENDAR component.  See RFC 2445 section 4.7.4 for details.</resolution>
        <resolution error="prodIDRequiredError">Add a PRODID property to the VCALENDAR.  See RFC 2445 section 4.7.3 for details.</resolution>
        <resolution error="prodIDOnlyOnceError">Remove the second PRODID property from the VCALENDAR component.  See RFC 2445 section 4.7.4 for details.</resolution>
    </resolutions>    
</language>

=== mdavid/DDay-iCal-svn/DDay.iCal.Validator/iCalValid/icalvalidSchema/rules/RFC2445/4.6.1/eventCommentProperty.xml
<?xml version="1.0" encoding="utf-8"?>
<rule
    name="eventCommentProperty"
    xmlns="http://icalvalid.wikidot.com/validation"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://icalvalid.wikidot.com/validation ../../../schema.xsd">
    <!--
    Section 4.6.1:
    ; the following are optional,
    ; and MAY occur more than once

    attach / attendee / categories / comment /
    contact / exdate / exrule / rstatus / related /
    resources / rdate / rrule / x-prop
    -->    
    <pass>
        <![CDATA[BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
END:VEVENT
END:VCALENDAR]]>
    </pass>

    <pass>
        <![CDATA[BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
COMMENT:The meeting really needs to include both ourselves 
 and the customer. We can't hold this  meeting without them. 
 As a matter of fact\, the venue for the meeting ought to be at 
 their site. - - John
END:VEVENT
END:VCALENDAR]]>
    </pass>

    <pass>
        <![CDATA[BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
COMMENT:The meeting really needs to include both ourselves 
 and the customer. We can't hold this  meeting without them. 
 As a matter of fact\, the venue for the meeting ought to be at 
 their site. - - John
COMMENT:Another.
END:VEVENT
END:VCALENDAR]]>
    </pass>

    <pass>
        <![CDATA[BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
COMMENT:The chancellor responded with a courteous\, "No comment."
END:VEVENT
END:VCALENDAR]]>
    </pass>

    <!-- 
    Section 4.3.11:
    text       = *(TSAFE-CHAR / ":" / DQUOTE / ESCAPED-CHAR)
    -->
    
    <!-- Backslashes must be escaped -->
    <fail
        error="textEscapeBackslashesError">
        <![CDATA[BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
COMMENT:Find at C:\Some\Path\To\A\File.txt
END:VEVENT
END:VCALENDAR]]>
    </fail>

    <!-- Commas must be escaped -->
    <fail
        error="textEscapeCommasError">
        <![CDATA[BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
COMMENT:The Lion, the Witch, and the Wardrobe
END:VEVENT
END:VCALENDAR]]>
    </fail>

    <!-- Semicolons must be escaped -->
    <fail
        error="textEscapeSemicolonsError">
        <![CDATA[BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
COMMENT:My comment;with a semicolon.
END:VEVENT
END:VCALENDAR]]>
    </fail>
</rule>
